name: Validate

on:
  workflow_call:
    inputs:
      cache-build:
        type: boolean

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    - run: echo ${{ inputs.cache-build }}

    - name: Cache Build
      if: ${{ inputs.cache-build }} == 'true'
      uses: actions/cache@v3
      with:
        path: |
          ./build
        key: build-${{ github.sha }}