name: Deploy

on:
  workflow_run:
    workflows: ['Release']
    branches: [main]
    types: 
      - completed

jobs:  
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build.yml

  check-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ./build
          key: build-${{ github.sha }}
      - run: |
          ls -a
          cd build
          ls -a
          echo 'ok'
