name: Release

on: 
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump type'     
        required: true
        default: 'minor' 
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Config Git
        env:
          NPM_SECRET: ${{ secrets.NPM_SECRET }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install
        run: yarn --frozen-lockfile

      - name: Release it
        run: yarn release ${{ github.event.inputs.bump_type }}
