name: Release

on: 
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump type'     
        required: true
        default: 'minor' 
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Cache build
      uses: actions/cache@v2
      with:
        path: ./build
        key: build-${{ github.sha }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Config Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install
        run: yarn --frozen-lockfile

      - name: Check
        run: git status

      - name: Release it
        run: yarn release ${{ github.event.inputs.bump_type }}

  publish:
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: ./build
          key: build-${{ github.sha }}    

      - name: Check
        run: ls

