name: Validate

on:
  workflow_call:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install
        run: yarn --frozen-lockfile
      
      - name: Lint
        run: yarn lint
      
      - name: Format
        run: yarn format
  
  build:
    uses: ./.github/workflows/build.yml

  check-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ./build
          key: build-${{ hashFiles('yarn.lock') }}
      - run: ls -a

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0

  #   - name: Setup Node
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '16'
  #       cache: 'yarn'

  #   - name: Install
  #     run: yarn --frozen-lockfile

  #   - name: Build
  #     run: yarn build